### ISSUE TITLE
Show Issues on the left panel

### ISSUE THREAD

**Issue by m0sth8** [bearded-web/frontend#40]
For example:
![2015-02-06 10-42-19 dasboard bearded](https://cloud.githubusercontent.com/assets/470078/6080154/e249a832-adec-11e4-94e6-71fc5d1878f3.png)
I can give you this fields in target object.

**Comment by slonoed** [comment]
@m0sth8 nice idea. Maybe I make view slightly difer.

**Comment by m0sth8** [comment]
Sure, it's just an example.

**Comment by m0sth8** [comment]
I will return a field summaryReport in target object

```
{
  "summaryReport": {
    "issues": {"high": 2, "medium": 3, "info": 4}
    ...
  }
}
```

https://github.com/bearded-web/bearded/issues/26
